### ISSUE TITLE
Testing for Linux, Windows and Darwin

### ISSUE THREAD

**Issue by caffeine-addictt** [caffeine-addictt/waku#26]
Testing for the 3 major OSes (Linux, Windows & Darwin).
PR welcome

## Track

- PR #30 
- Issue #23 
- Waiting on #28 
- Waiting on #33 
- Merging after #29

**Comment by caffeine-addictt** [comment]
@LyubomirT Any idea on how to optimize in node?

ReadFileSync writes the contents of each file into memory, but i believe it would be better to implement this with streams. I haven't been successful so far though...

You can see the failed implementation merged in #36

**Comment by LyubomirT** [comment]
Streaming actually sounds like a great idea, I'll see what I can do and will try to add the implementation to my fork if I succeed. Can't guarantee anything for now, though.

**Comment by LyubomirT** [comment]
> Any idea on how to optimize in node?

However, personally, I don't think optimization will matter much here, since all the files combined likely won't eat more than 10KB of memory.

**Comment by caffeine-addictt** [comment]
> > Any idea on how to optimize in node?
> 
> However, personally, I don't think optimization will matter much here, since all the files combined likely won't eat more than 10KB of memory.

True. Although apart from a lower memory usage, we would be able to boost runtime performance.

**Comment by caffeine-addictt** [comment]
Alright.
I got it stable in Archlinux after #38. 🥳 

Is it working fine on your side?

**Comment by LyubomirT** [comment]
> Alright.
> I got it stable in Archlinux after #38. 🥳 
> 
> Is it working fine on your side?

Glad to hear it works well! Can't really use it in Windows 11 for some reason, but maybe it's just the merge conflict.

**Comment by caffeine-addictt** [comment]
Perhaps your fork is outdated? 🤔

**Comment by LyubomirT** [comment]
> Perhaps your fork is outdated? 🤔

It was indeed outdated, but due to how late I noticed that, I got a merge conflict, and, well, it all broke.

===

I managed to get your version to work, though :D

**Comment by caffeine-addictt** [comment]
I'll hold off on writing tests until I've added a few more features. PRs still welcome though ❤️

**Comment by caffeine-addictt** [comment]
> > > Any idea on how to optimize in node?
> > 
> > 
> > However, personally, I don't think optimization will matter much here, since all the files combined likely won't eat more than 10KB of memory.
> 
> True. Although apart from a lower memory usage, we would be able to boost runtime performance.

@LyubomirT lets move this to #46 :>

**Comment by caffeine-addictt** [comment]
Including this is v2 in Go.

For v2, I think it'd be great if we had some blackbox testing with docker and bash too.
@LyubomirT lmk if you're still up for it! 😄
